services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:example@db:5432/sumzy
      - DIRECT_URL=postgres://postgres:example@db:5432/sumzy
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - sumzy

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sumzy
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sumzy

volumes:
  pgdata:

networks:
  sumzy:
    driver: bridge
